apiVersion: v1
data:
  application.yml: |
    server:
        port: 8087

    spring:
        crm:
            datasource:
                jdbc-url: jdbc:oracle:thin:@172.20.204.3:1521/D2CRMSIT
                password: test_read
                username: test_read
                driver-class: oracle.jdbc.driver.OracleDriver
        datasource:
            jdbc-url: jdbc:mysql://35.190.164.195:3306/test_memsql
            password: ''
            username: root
        jpa:
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5Dialect
        kafka:
            template:
                default-topic: profilemgmt-customer
            producer:
                bootstrap-servers: http://139.59.37.4:9092
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            properties:
                schema.registry.url: http://139.59.37.4:8081
            admin:
                properties:
                    bootstrap.servers: 139.59.37.4:9092
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://139.59.37.4:9092}
        zipkin:
            sender:
                type: kafka
        sleuth:
            sammpler:
                rate: 1000

    token:
        expiration:
            time: 1800000
        secret:
            key: ${SECRET_KEY}

    logger:
        kafka:
            topic: customercreationlogs
            bootstrap-servers: ${spring.kafka.bootstrap-servers}
            retries: 2

    kafka:
        topic: profilemgmt-customer
kind: ConfigMap
metadata:
  name: customer-verification-api-v2
  namespace: plm

