apiVersion: v1
data:
  application.yml: |+
    server:
        port: 8087
    spring:
        datasource:
            password: ''
            url: jdbc:mysql://139.59.37.4:3306/test_memsql
            username: root
        jpa:
            hibernate:
                ddl-auto: update
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5Dialect
            show-sql: true
        kafka:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://139.59.37.4:9092}
        zipkin:
            sender:
                type: kafka
        sleuth:
            sammpler:
                rate: 1000
    token:
        expiration:
            time: 1800000
        secret:
            key: ${SECRET_KEY}


kind: ConfigMap
metadata:
  name: customer-verification-api
  namespace: plm

