apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: customer-verification-api-v2
  labels:
    app: customer-verification-api-v2
spec:
  replicas: 1
  selector:
    app: customer-verification-api-v2
  template:
    metadata:
      labels:
        app: customer-verification-api-v2
    spec:
      containers:
        - name: customer-verification-api-v2
          image: bhargavasarva/customer-verification-api:v10
          ports:
          - containerPort: 8087
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: secret-key
  

---
apiVersion: v1
kind: Service
metadata:
  name: customer-verification-api-v2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8087
      name: http
  selector:
    app: customer-verification-api-v2

