apiVersion: v1
data:
  application.yml: |
    server:
      port: 8086

    spring:
      datasource:
        url: jdbc:mysql://35.190.164.195:3306/test_memsql
        username: root
        password: ''
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
      zipkin:
        sender:
          type: kafka
      sleuth:
        sampler:
          rate: 1000

    token:
      expiration.time: 1800000
      secret.key: ${SECRET_KEY}

    logger:
      kafka:
        topic: customercreationlogs
        bootstrap-servers: ${spring.kafka.bootstrap-servers}
        retries: 2
kind: ConfigMap
metadata:
  name: login-api-v2
  namespace: plm

