apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: login-api
  labels:
    app: login-api
spec:
  replicas: 1
  selector:
    app: login-api
  template:
    metadata:
      labels:
        app: login-api
    spec:
      containers:
        - name: login-api
          image: bhargavasarva/login-api:v3
          ports:
          - containerPort: 8086
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret 
                  key: secret-key  

---
apiVersion: v1
kind: Service
metadata:
  name: login-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8086
      name: http
  selector:
    app: login-api

